import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-patent-license-royalty-audit",
  "engine": "recovery",
  "title": "Patent License Royalty Audit",
  "shortTitle": "Patent License Royalty Audit",
  "tagline": "Recover patent royalties through product coverage, net-sales, rate, minimum, sublicense, and territory reconciliation.",
  "industry": "Intellectual Property Revenue Assurance",
  "buyer": "Patent owners, licensors, and technology companies",
  "uiPort": 4740,
  "apiPort": 5740,
  "accent": "#1d4ed8",
  "currency": "USD",
  "primaryOutcome": "Patent License Royalty Audit converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect license agreements, patent families, licensed products, sales, net-sales deductions, territories, royalty rates, minimums, sublicenses, reports, and payments in one accountable workflow. Recover patent royalties through product coverage, net-sales, rate, minimum, sublicense, and territory reconciliation.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Patent License Royalty Audit evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("patent-license-library","PLR01","Patent license library","Execute patent license library using license agreements, patent families, licensed products, sales, net-sales deductions, territories, royalty rates, minimums, sublicenses, reports, and payments.","Produce a governed patent license library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Licensee / Patent Portfolio","text","Licensee / Patent Portfolio · Standard Case"],["caseReference","Patent license library Reference","text","PLR01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1841250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2227913],["domainDriver","Royalty Basis","select","Net sales",["Net sales","Per unit","Minimum guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patent license library case","Patent family registry case","Licensed product mapping case","Licensee sales ingestion case","Gross sales validation case"]}),
feature("patent-family-registry","PLR02","Patent family registry","Execute patent family registry using license agreements, patent families, licensed products, sales, net-sales deductions, territories, royalty rates, minimums, sublicenses, reports, and payments.","Produce a governed patent family registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Licensee / Patent Portfolio","text","Licensee / Patent Portfolio · Standard Case"],["caseReference","Patent family registry Reference","text","PLR02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1841250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2227913],["domainDriver","Royalty Basis","select","Net sales",["Net sales","Per unit","Minimum guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patent license library case","Patent family registry case","Licensed product mapping case","Licensee sales ingestion case","Gross sales validation case"]}),
feature("licensed-product-mapping","PLR03","Licensed product mapping","Execute licensed product mapping using license agreements, patent families, licensed products, sales, net-sales deductions, territories, royalty rates, minimums, sublicenses, reports, and payments.","Produce a governed licensed product mapping decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Licensee / Patent Portfolio","text","Licensee / Patent Portfolio · Standard Case"],["caseReference","Licensed product mapping Reference","text","PLR03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1841250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2227913],["domainDriver","Royalty Basis","select","Net sales",["Net sales","Per unit","Minimum guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patent license library case","Patent family registry case","Licensed product mapping case","Licensee sales ingestion case","Gross sales validation case"]}),
feature("licensee-sales-ingestion","PLR04","Licensee sales ingestion","Execute licensee sales ingestion using license agreements, patent families, licensed products, sales, net-sales deductions, territories, royalty rates, minimums, sublicenses, reports, and payments.","Produce a governed licensee sales ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Licensee / Patent Portfolio","text","Licensee / Patent Portfolio · Standard Case"],["caseReference","Licensee sales ingestion Reference","text","PLR04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1841250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2227913],["domainDriver","Royalty Basis","select","Net sales",["Net sales","Per unit","Minimum guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patent license library case","Patent family registry case","Licensed product mapping case","Licensee sales ingestion case","Gross sales validation case"]}),
feature("gross-sales-validation","PLR05","Gross sales validation","Execute gross sales validation using license agreements, patent families, licensed products, sales, net-sales deductions, territories, royalty rates, minimums, sublicenses, reports, and payments.","Produce a governed gross sales validation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Licensee / Patent Portfolio","text","Licensee / Patent Portfolio · Standard Case"],["caseReference","Gross sales validation Reference","text","PLR05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1841250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2227913],["domainDriver","Royalty Basis","select","Net sales",["Net sales","Per unit","Minimum guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patent license library case","Patent family registry case","Licensed product mapping case","Licensee sales ingestion case","Gross sales validation case"]}),
feature("net-sales-deduction-audit","PLR06","Net-sales deduction audit","Execute net-sales deduction audit using license agreements, patent families, licensed products, sales, net-sales deductions, territories, royalty rates, minimums, sublicenses, reports, and payments.","Produce a governed net-sales deduction audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Licensee / Patent Portfolio","text","Licensee / Patent Portfolio · Standard Case"],["caseReference","Net-sales deduction audit Reference","text","PLR06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1841250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2227913],["domainDriver","Royalty Basis","select","Net sales",["Net sales","Per unit","Minimum guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patent license library case","Patent family registry case","Licensed product mapping case","Licensee sales ingestion case","Gross sales validation case"]}),
feature("territory-eligibility","PLR07","Territory eligibility","Execute territory eligibility using license agreements, patent families, licensed products, sales, net-sales deductions, territories, royalty rates, minimums, sublicenses, reports, and payments.","Produce a governed territory eligibility decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Licensee / Patent Portfolio","text","Licensee / Patent Portfolio · Standard Case"],["caseReference","Territory eligibility Reference","text","PLR07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1841250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2227913],["domainDriver","Royalty Basis","select","Net sales",["Net sales","Per unit","Minimum guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patent license library case","Patent family registry case","Licensed product mapping case","Licensee sales ingestion case","Gross sales validation case"]}),
feature("royalty-rate-calculation","PLR08","Royalty rate calculation","Execute royalty rate calculation using license agreements, patent families, licensed products, sales, net-sales deductions, territories, royalty rates, minimums, sublicenses, reports, and payments.","Produce a governed royalty rate calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Licensee / Patent Portfolio","text","Licensee / Patent Portfolio · Standard Case"],["caseReference","Royalty rate calculation Reference","text","PLR08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1841250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2227913],["domainDriver","Royalty Basis","select","Net sales",["Net sales","Per unit","Minimum guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patent license library case","Patent family registry case","Licensed product mapping case","Licensee sales ingestion case","Gross sales validation case"]}),
feature("per-unit-calculation","PLR09","Per-unit calculation","Execute per-unit calculation using license agreements, patent families, licensed products, sales, net-sales deductions, territories, royalty rates, minimums, sublicenses, reports, and payments.","Produce a governed per-unit calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Licensee / Patent Portfolio","text","Licensee / Patent Portfolio · Standard Case"],["caseReference","Per-unit calculation Reference","text","PLR09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1841250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2227913],["domainDriver","Royalty Basis","select","Net sales",["Net sales","Per unit","Minimum guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patent license library case","Patent family registry case","Licensed product mapping case","Licensee sales ingestion case","Gross sales validation case"]}),
feature("minimum-guarantee","PLR10","Minimum guarantee","Execute minimum guarantee using license agreements, patent families, licensed products, sales, net-sales deductions, territories, royalty rates, minimums, sublicenses, reports, and payments.","Produce a governed minimum guarantee decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Licensee / Patent Portfolio","text","Licensee / Patent Portfolio · Standard Case"],["caseReference","Minimum guarantee Reference","text","PLR10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1841250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2227913],["domainDriver","Royalty Basis","select","Net sales",["Net sales","Per unit","Minimum guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patent license library case","Patent family registry case","Licensed product mapping case","Licensee sales ingestion case","Gross sales validation case"]}),
feature("sublicense-income-share","PLR11","Sublicense income share","Execute sublicense income share using license agreements, patent families, licensed products, sales, net-sales deductions, territories, royalty rates, minimums, sublicenses, reports, and payments.","Produce a governed sublicense income share decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Licensee / Patent Portfolio","text","Licensee / Patent Portfolio · Standard Case"],["caseReference","Sublicense income share Reference","text","PLR11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1841250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2227913],["domainDriver","Royalty Basis","select","Net sales",["Net sales","Per unit","Minimum guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patent license library case","Patent family registry case","Licensed product mapping case","Licensee sales ingestion case","Gross sales validation case"]}),
feature("royalty-report-audit","PLR12","Royalty report audit","Execute royalty report audit using license agreements, patent families, licensed products, sales, net-sales deductions, territories, royalty rates, minimums, sublicenses, reports, and payments.","Produce a governed royalty report audit decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Licensee / Patent Portfolio","text","Licensee / Patent Portfolio · Standard Case"],["caseReference","Royalty report audit Reference","text","PLR12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1841250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2227913],["domainDriver","Royalty Basis","select","Net sales",["Net sales","Per unit","Minimum guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patent license library case","Patent family registry case","Licensed product mapping case","Licensee sales ingestion case","Gross sales validation case"]}),
feature("licensee-examination-workflow","PLR13","Licensee examination workflow","Execute licensee examination workflow using license agreements, patent families, licensed products, sales, net-sales deductions, territories, royalty rates, minimums, sublicenses, reports, and payments.","Produce a governed licensee examination workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Licensee / Patent Portfolio","text","Licensee / Patent Portfolio · Standard Case"],["caseReference","Licensee examination workflow Reference","text","PLR13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1841250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2227913],["domainDriver","Royalty Basis","select","Net sales",["Net sales","Per unit","Minimum guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patent license library case","Patent family registry case","Licensed product mapping case","Licensee sales ingestion case","Gross sales validation case"]}),
feature("cash-reconciliation","PLR14","Cash reconciliation","Execute cash reconciliation using license agreements, patent families, licensed products, sales, net-sales deductions, territories, royalty rates, minimums, sublicenses, reports, and payments.","Produce a governed cash reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Licensee / Patent Portfolio","text","Licensee / Patent Portfolio · Standard Case"],["caseReference","Cash reconciliation Reference","text","PLR14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1841250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2227913],["domainDriver","Royalty Basis","select","Net sales",["Net sales","Per unit","Minimum guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patent license library case","Patent family registry case","Licensed product mapping case","Licensee sales ingestion case","Gross sales validation case"]}),
feature("patent-product-analytics","PLR15","Patent product analytics","Execute patent product analytics using license agreements, patent families, licensed products, sales, net-sales deductions, territories, royalty rates, minimums, sublicenses, reports, and payments.","Produce a governed patent product analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Licensee / Patent Portfolio","text","Licensee / Patent Portfolio · Standard Case"],["caseReference","Patent product analytics Reference","text","PLR15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1841250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2227913],["domainDriver","Royalty Basis","select","Net sales",["Net sales","Per unit","Minimum guarantee"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Patent license library case","Patent family registry case","Licensed product mapping case","Licensee sales ingestion case","Gross sales validation case"]})
]);
